# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title: Srisupang
tagline: "AMLR Lab"
description: "Assistant Professor at CPE-SWU. Specialized in Computer Vision, AI, and ML. Founder of AMLR Lab"
url: https://mssrisupang.github.io
baseurl: /

author:
  name: "Srisupang Thewsuwan"
  url:

paginate: 5

# Custom vars
version: 1.1.0

github:
  repo: https://github.com/mssrisupang
